version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # update package.json
    version_requirement_updates: "widen_ranges"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
