version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build-and-test:  
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Run linter 
          command: yarn lint 
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build
          command: yarn compile 
      - run:
          name: Pack
          command: yarn pack
      - run:
          name: Copy package to artifacts directory 
          command: mkdir -p dist && cp splunk-otel-v*.tgz dist
      - store_artifacts:
          path: dist/
          destination: built-packages
      - persist_to_workspace:
          root: ~/
          paths: project/
      - run:
          name: Report coverage 
          command: yarn codecov 
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Authenticate npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          command: yarn publish 

workflows:
  build: 
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
      - release:
          requires:
            - build-and-test 
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/